name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        cache: pnpm
        node-version: 24
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
