jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare
      - run: pnpm format-check

name: Format

on:
  pull_request: ~
  push:
    branches:
      - main
